Repository BETSRG/GHEDesigner, pull requests merged in 2024-09, with the labels that each got.

#113 Modernize project management to use pyproject.toml
  .github/contributing.md
  .github/workflows/flake8.yml
  .github/workflows/install.yml
  .github/workflows/tests.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  demos/input_bldg0000056_odd_loads.json
  demos/issue_97_interp_out_of_range.json
  docs/conf.py
  ghedesigner/borehole_heat_exchangers.py
  ghedesigner/coordinates.py
  ghedesigner/design.py
  ghedesigner/domains.py
  ghedesigner/feature_recognition.py
  ghedesigner/geometry.py
  ghedesigner/gfunction.py
  ghedesigner/ground_heat_exchangers.py
  ghedesigner/ground_loads.py
  ghedesigner/manager.py
  ghedesigner/media.py
  ghedesigner/output.py
  ghedesigner/radial_numerical_borehole.py
  ghedesigner/rowwise.py
  ghedesigner/search_routines.py
  ghedesigner/shape.py
  ghedesigner/simulation.py
  ghedesigner/tests/expected_demo_results.json
  ghedesigner/tests/test_base_case.py
  ghedesigner/tests/test_compute_bh_resistance.py
  ghedesigner/tests/test_compute_g_function_sim_and_size.py
  ghedesigner/tests/test_compute_live_g_function_sim_and_size.py
  ghedesigner/tests/test_create_input_files.py
  ghedesigner/tests/test_data/rowwise_reference_values.csv
  ghedesigner/tests/test_demo_files.py
  ghedesigner/tests/test_equiv_pipes.py
  ghedesigner/tests/test_find_design_bi_rectangle.py
  ghedesigner/tests/test_find_design_bi_rectangle_constrained.py
  ghedesigner/tests/test_find_design_bi_zoned_rectangle.py
  ghedesigner/tests/test_find_design_near_square.py
  ghedesigner/tests/test_find_design_near_square_2.py
  ghedesigner/tests/test_find_design_near_square_multiyear.py
  ghedesigner/tests/test_find_design_rectangle.py
  ghedesigner/tests/test_find_design_rowwise.py
  ghedesigner/tests/test_loads.py
  ghedesigner/tests/test_radial_numerical_borehole.py
  ghedesigner/tests/test_rowwise.py
  ghedesigner/tests/test_simulate_ghe.py
  ghedesigner/tests/test_size_limits.py
  ghedesigner/utilities.py
  ghedesigner/validate.py
  pyproject.toml
  requirements.txt
  ruff.toml
  scripts/update_demo_results.py
  scripts/update_version.py
  setup.cfg
  setup.py
  uv.lock
Labels: refactoring

#119 Cleanup Odd Warning Messages
  ghedesigner/gfunction.py
  ghedesigner/output.py
  ghedesigner/tests/test_compute_g_function_sim_and_size.py
  ghedesigner/tests/test_data/GLHEPRO_gFunctions_12x13.json
  ghedesigner/tests/test_demo_files.py
Labels: bug

#117 Follow up fixes to the project-management changes recently enacted
  README.md
  docs/conf.py
  ghedesigner/gfunction.py
  ghedesigner/manager.py
  ghedesigner/tests/test_demo_files.py
  requirements.txt
Labels: bug

#121 Resolve documentation deployment issues
  .github/workflows/mkdocs.yml
Labels: documentation

#126 Change schema `units` field to `format` so it renders properly on the docs site
  .readthedocs.yml
  ghedesigner/schemas/borehole.schema.json
  ghedesigner/schemas/design.schema.json
  ghedesigner/schemas/file_structure.schema.json
  ghedesigner/schemas/fluid.schema.json
  ghedesigner/schemas/geometric_bi_rectangle.schema.json
  ghedesigner/schemas/geometric_bi_rectangle_constrained.schema.json
  ghedesigner/schemas/geometric_bi_zoned_rectangle.schema.json
  ghedesigner/schemas/geometric_near_square.schema.json
  ghedesigner/schemas/geometric_rectangle.schema.json
  ghedesigner/schemas/geometric_rowwise.schema.json
  ghedesigner/schemas/grout.schema.json
  ghedesigner/schemas/loads.schema.json
  ghedesigner/schemas/pipe_coaxial.schema.json
  ghedesigner/schemas/pipe_single_double_u_tube.schema.json
  ghedesigner/schemas/simulation.schema.json
  ghedesigner/schemas/soil.schema.json
  mkdocs.yml
Labels: documentation
